name: Sales change
description: null
tableName: monthly_popular_books
updatedAt: "2025-05-21T02:41:54.890Z"
metricQuery:
  exploreName: monthly_popular_books
  dimensions:
    - monthly_popular_books_amount
    - monthly_popular_books_title
    - monthly_popular_books_year_month_month
  metrics: []
  filters: {}
  sorts:
    - fieldId: monthly_popular_books_year_month_month
      descending: true
  limit: 500
  metricOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: cartesian
  config:
    layout:
      xField: monthly_popular_books_year_month_month
      yField:
        - monthly_popular_books_amount
    eChartsConfig:
      series:
        - type: line
          encode:
            xRef:
              field: monthly_popular_books_year_month_month
            yRef:
              field: monthly_popular_books_amount
          smooth: true
          showSymbol: true
          yAxisIndex: 0
          isFilteredOut: false
      tooltip: ""
slug: sales-change
tableConfig:
  columnOrder:
    - monthly_popular_books_amount
    - monthly_popular_books_title
    - monthly_popular_books_year_month_month
spaceSlug: shared
version: 1
downloadedAt: "2025-05-22T12:50:33.684Z"
